model: replicate/flux-dev-internal-model
test_model: replicate/test-flux-dev
predict:
  compare_outputs: false  # TODO(andreas): why doesn't this work?
  predict_timeout: 600
  test_cases:

    # basic
    - inputs:
        prompt: A formula one car
        num_outputs: 1
        num_inference_steps: 28
        guidance: 3.5
        seed: 5259
        output_format: jpg
      match_prompt: A 1024x1024px jpg image of a formula one car

    # 4 outputs
    - inputs:
        prompt: A formula one car
        num_outputs: 4
        num_inference_steps: 20
        guidance: 1.0
        seed: 5259
        output_format: png
      match_prompt: Four png images

    # disable safety checker
    - inputs:
        prompt: A formula one car
        num_outputs: 1
        num_inference_steps: 20
        guidance: 1.0
        seed: 5259
        output_format: png
        disable_safety_checker: true
      match_prompt: A 1024x1024px png image of a formula one car

    # img2img
    - inputs:
        prompt: A formula one car
        num_outputs: 1
        num_inference_steps: 20
        guidance: 1.0
        seed: 5259
        output_format: png
        image: "https://storage.googleapis.com/cog-safe-push-public/fast-car.jpg"
        prompt_strength: 0.9
      match_prompt: A 1024x640px png image of a formula one car

    # aspect ratio
    - inputs:
        prompt: A formula one car
        num_outputs: 1
        num_inference_steps: 20
        guidance: 1.0
        seed: 5259
        output_format: png
        aspect_ratio: "3:2"
      match_prompt: A 1216x832px png image of a formula one car

    # go slow
    - inputs:
        prompt: A formula one car
        num_outputs: 1
        num_inference_steps: 28
        guidance: 3.5
        seed: 5259
        output_format: jpg
        go_fast: false
      match_prompt: A 1024x1024px jpg image of a formula one car

    # slow img2img, 4 outputs
    - inputs:
        prompt: A journey to the middle of the earth
        num_outputs: 4
        num_inference_steps: 20
        guidance: 3.5
        seed: 5259
        output_format: jpg
        go_fast: false
        image: "https://storage.googleapis.com/cog-safe-push-public/fast-car.jpg"
      match_prompt: 4 jpg images

  fuzz:
    iterations: 10
